### ISSUE TITLE
ERROR (Error): Incorrect padding

### ISSUE THREAD

**Issue by Eloquenz** [Endogen/Telegram-Kraken-Bot#11]
Hello,

I tried to set-up your Bot and everything worked so far. 
The Bot is up and Running and it is Up-to-date. The /bot Button works, I can update, reconfigure and restart. 
However,  on every other button I press I get the response "ERROR (Error): Incorrect padding".

For example:
I press /balance -> Retrieving data... -> ERROR (Error): Incorrect padding
In the command line it shows the error like this: "ERROR - root - ERROR (Error): Incorrect padding"

I am not experienced with stuff like this, so I am sorry if it is something trivial.

Thanks.

**Comment by Endogen** [comment]
Could you please verify that you have the _correct_ two keys (two lines) in the `kraken.key` file? In my case the key in the second line ends with `==`. If i remove that, i get the same behavior as you

**Comment by Eloquenz** [comment]
Oh my god, this is embarrassing. I copied the keys the wrong way. I copy and pasted them again and now it works. Sorry for bothering and thank you very much! 
Regards

**Comment by Endogen** [comment]
You're welcome! Happy that i could help you :)
