### ISSUE TITLE
not working since kraken.com update

### ISSUE THREAD

**Issue by ratio91** [Endogen/Telegram-Kraken-Bot#19]
is it just me or does the program not work at all (does not start up) since kraken.com had its last major update?
already updated everything, no effect.

**Comment by Endogen** [comment]
Should work just fine. Today or tomorrow i will release a bigger update (possible to trade to a different currency and not only to fiat currencies). I will make sure that it's working fine before releasing but again, for me everything works just fine.

If you don't want to wait, here is what you can do:
1. remove the bot and the config
2. download the newest version - not release 0.8.0, but newest version from master
3. set up config again
4. try it again :)

If that doesn't work, set `log_to_file` in config to `true`, start up the bot and after it doesn't work send me the logfile. But if you do that, please search for the bot-token in the logfile and remove it from there before you post the file here (the configuration is logged in the logfile)

**Comment by Endogen** [comment]
Did you resolve your issue? I'm currently still bugfixing the new version

**Comment by ratio91** [comment]
solved. thx!
