### ISSUE TITLE
KeyError: 'decimals'

### ISSUE THREAD

**Issue by hliasa** [Endogen/Telegram-Kraken-Bot#22]
Hello and thanks for this project.
After updating to the latest version I encountered the following problem:
`Traceback (most recent call last):
  File "telegram_kraken_bot.py", line 1901, in <module>
    def trim_zeros(value_to_trim, decimals=config["decimals"]):
KeyError: 'decimals'
`
It seems like you forgot to add the **decimals** variable in the config.json file.

**Comment by Endogen** [comment]
Oh yes, i forgot to update the config... Will update it later today.  Thanks for reporting! :+1:

**Comment by Endogen** [comment]
I updated the `config.json` file. Thanks again for reporting! Please make sure that you use the current version because there are some changes. I didn't only add `"decimals": 6,`, there some more things

**Comment by Endogen** [comment]
I will close this issue. Please feel free to reopen it if needed
